chore(deps): update dependency cypress to v9 (#8045)
[![WhiteSource Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [cypress](https://togithub.com/cypress-io/cypress) | [`^8.7.0` -> `^9.0.0`](https://renovatebot.com/diffs/npm/cypress/8.7.0/9.2.1) | [![age](https://badges.renovateapi.com/packages/npm/cypress/9.2.1/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/cypress/9.2.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/cypress/9.2.1/compatibility-slim/8.7.0)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/cypress/9.2.1/confidence-slim/8.7.0)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>cypress-io/cypress</summary>

### [`v9.2.1`](https://togithub.com/cypress-io/cypress/releases/v9.2.1)

[Compare Source](https://togithub.com/cypress-io/cypress/compare/v9.2.0...v9.2.1)

*Released 1/10/2022*

**Bugfixes:**

-   Fixed a regression in [9.2.0](https://docs.cypress.io/guides/references/changelog#&#8203;9-2-0) to keep
    Cypress open after each spec finishes when the `--headed --no-exit` flags are
    passed to `cypress run`. Fixes
    [#&#8203;19485](https://togithub.com/cypress-io/cypress/issues/19485).
-   Improve heuristic for verifying when the `--openssl-legacy-provider` option
    should be passed to the plugins' child process when the system Node version is
    v17+. This prevents Cypress from crashing when a user has Node 17 installed
    which was built with OpenSSL v1. Fixes
    [#&#8203;19320](https://togithub.com/cypress-io/cypress/issues/19320).
-   Correctly cast the `CYPRESS_VERIFY_TIMEOUT` environment variable as a number
    so Cypress will no longer throw
    `TypeError: Expected the timeout option to be a non-negative integer`. Fixes
    [#&#8203;19476](https://togithub.com/cypress-io/cypress/issues/19476).

**Dependency Updates:**

-   Update pinned resolution of `cli-table3` from `~0.6.0` to `~0.6.1` to avoid
    problems with the bug introduced in the
    [colors.js v1.4.44-liberty-2 release](https://togithub.com/Marak/colors.js/issues/285).
    Addresses [#&#8203;19624](https://togithub.com/cypress-io/cypress/issues/19624).

### [`v9.2.0`](https://togithub.com/cypress-io/cypress/releases/v9.2.0)

[Compare Source](https://togithub.com/cypress-io/cypress/compare/v9.1.1...v9.2.0)

*Released 12/20/2021*

**Features:**

-   Cypress will throw an error when a user attempts to update a configuration
    value at run-time using either the Test Configuration or using
    `Cypress.config()` that is a
    [readonly option](https://docs.cypress.io/guides/references/configuration#Test-Configuration).
    Addresses [#&#8203;6407](https://togithub.com/cypress-io/cypress/issues/6407) and
    [#&#8203;19001](https://togithub.com/cypress-io/cypress/issues/19001).
-   A `timeout` option has been added to the `cy.writeFile()` command, with a
    default value of `defaultCommandTimeout`. Addresses
    [#&#8203;3350](https://togithub.com/cypress-io/cypress/issues/3350).
-   The default `maxHttpBufferSize` for the internal socket server has been
    increased to
    [Node's maximum Buffer size](https://nodejs.org/api/buffer.html#bufferconstantsmax_length)
    (size varies by OS) to allow large file writes with `cy.writeFile()`.
    Addresses [#&#8203;19140](https://togithub.com/cypress-io/cypress/issues/19140).
-   Add `CYPRESS_VERIFY_TIMEOUT` environment variable to override the timeout
    duration of the `verify` command. Addresses
    [#&#8203;18290](https://togithub.com/cypress-io/cypress/issues/18290).

**Bugfixes:**

-   Prevent unnecessary snapshotting when running default assertions that would
    unnecessarily increase CPU use in `cypress open` mode which lead to out of
    memory crashes on certain browsers. Fixes
    [#&#8203;18549](https://togithub.com/cypress-io/cypress/issues/18549).
-   Removed automatic retries for failed HTTP requests through the proxy. This
    fixes an issue where failed requests could be re-sent too many times in some
    conditions. This change could increase the number of failed requests that your
    app sees. Fixes [#&#8203;19043](https://togithub.com/cypress-io/cypress/issues/19043).
-   Reduced the occurrence of an issue where logs for `fetch` and `xhr` requests
    could be associated with the wrong request. Fixes
    [#&#8203;19043](https://togithub.com/cypress-io/cypress/issues/19043).
-   Tests that are skipped within `then` blocks will no longer throw errors
    causing the test to fail. Tests that are skipped outside of `then` blocks will
    no longer trigger the fail event. This will prevent screenshots from happening
    from errors thrown by the fail event.Fixes
    [#&#8203;14867](https://togithub.com/cypress-io/cypress/issues/14867) and
    [#&#8203;17660](https://togithub.com/cypress-io/cypress/issues/17660).
-   Fixed a regression in [9.0.0](https://docs.cypress.io/guides/references/changelog#&#8203;9-0-0) where a
    fixture provided in a static response to `cy.intercept()` did not support
    passing `null` to encoding to read the fixture as a Buffer. This identified an
    undocumented 9.0.0 Breaking Change where the default read behavior of a
    fixture changed from a Buffer to being read with `utf8` encoding. Fixes
    [#&#8203;19344](https://togithub.com/cypress-io/cypress/issues/19344).
-   Fixed a regression in [9.0.0](https://docs.cypress.io/guides/references/changelog#&#8203;9-0-0) where
    `cy.contains()` attempted to ignore `<script>` and `<style>` elements found
    within `<body>`. by deleting them from the dom. This behavior was corrected to
    ignore the elements without deleting them. Fixes
    [#&#8203;19377](https://togithub.com/cypress-io/cypress/issues/19377).
-   Cypress will no longer crash when proxying an ill formed request. For example,
    if the application under test has a resource of `"http: //localhost/asset.js"`
    (notice the extraneous space), Cypress will now log a debug message and the
    asset will fail to load. Fixes
    [#&#8203;9220](https://togithub.com/cypress-io/cypress/issues/9220).
-   Correct `Cypress.Command.add()` and `Cypress.Command.override()` TypeScript
    types. Fixes [#&#8203;18879](https://togithub.com/cypress-io/cypress/issues/18879),
    [#&#8203;19095](https://togithub.com/cypress-io/cypress/issues/19095) and
    [#&#8203;18940](https://togithub.com/cypress-io/cypress/issues/18940).
    -   Custom command implementations typings take into account `prevSubject`
        variants.
    -   Custom command implementations now allows to NOT return a value.
    -   Custom command overwrites typings take into account `originalFn` function.
-   Add types for `Cypress.session.clearAllSavedSessions()`. Fixes
    [#&#8203;19363](https://togithub.com/cypress-io/cypress/issues/19363).

**Dependencies:**

-   Upgraded `ssri` from `6.0.1` to `6.0.2` to mitigate
    [ssri vulnerability](snyk.io/vuln/npm:ssri@6.0.1). Addressed in
    [#&#8203;19351](https://togithub.com/cypress-io/cypress/issues/19351).

### [`v9.1.1`](https://togithub.com/cypress-io/cypress/releases/v9.1.1)

[Compare Source](https://togithub.com/cypress-io/cypress/compare/v9.1.0...v9.1.1)

*Released 12/03/2021*

**Bugfixes:**

-   Fixed a regression in [9.1.0](https://docs.cypress.io/guides/references/changelog#&#8203;9-1-0) where our
    built binary didn't contain patches to some dependencies. Addressed in
    [#&#8203;19239](https://togithub.com/cypress-io/cypress/pull/19239). This fixed some
    issues including:
    -   Requests containing `~` will no longer be improperly encoded. Fixes
        [#&#8203;19083](https://togithub.com/cypress-io/cypress/issues/19083),
        [#&#8203;19084](https://togithub.com/cypress-io/cypress/issues/19084),
        [#&#8203;19115](https://togithub.com/cypress-io/cypress/issues/19115),
        [#&#8203;19096](https://togithub.com/cypress-io/cypress/issues/19096),
        [#&#8203;19178](https://togithub.com/cypress-io/cypress/issues/19178).
    -   A TypeError displaying `data.hasOwnProperty is not a function` will no
        longer throw in some situations. Fixes
        [#&#8203;19091](https://togithub.com/cypress-io/cypress/issues/19091).
    -   Empty extra hooks will no longer be sent as data when recording to the
        Dashboard. Fixes
        [#&#8203;19087](https://togithub.com/cypress-io/cypress/issues/19087).
    -   The Runner hanging when baseUrl is set to null to load a local file. Fixes
        [#&#8203;19105](https://togithub.com/cypress-io/cypress/issues/19105)
-   When using the default configuration of `"nodeVersion": "system"` with an
    installed system node >=17, Cypress will now work properly rather than throw
    an error incorrectly pointing to the user's plugin file. Fixes
    [#&#8203;18914](https://togithub.com/cypress-io/cypress/issues/18914).
-   Shadow DOM elements no longer error as hidden during actionability when the
    element is covered by its parent shadow root. Fixes
    [#&#8203;18008](https://togithub.com/cypress-io/cypress/issues/18008).
-   When using `.type()` events now correctly propagate out of the shadow DOM.
    Fixes [#&#8203;17531](https://togithub.com/cypress-io/cypress/issues/17531).
-   The `this` context is now properly preserved when overwriting `cy.clock()`.
    Fixes [#&#8203;19158](https://togithub.com/cypress-io/cypress/issues/19158).

**Dependencies:**

-   Upgraded `@cypress/request` from `2.88.7` to `2.88.10`. Addressed in
    [#&#8203;19099](https://togithub.com/cypress-io/cypress/issues/19099).

### [`v9.1.0`](https://togithub.com/cypress-io/cypress/releases/v9.1.0)

[Compare Source](https://togithub.com/cypress-io/cypress/compare/v9.0.0...v9.1.0)

*Released 11/22/2021*

**Features:**

-   A `CYPRESS` environment variable will be set to true in child processes where
    Cypress runs user code in Node.js. You can now detect that you're running in
    Cypress by looking for `process.env.CYPRESS`. Addresses
    [#&#8203;18805](https://togithub.com/cypress-io/cypress/issues/18805).

**Bugfixes:**

-   Specs with % in the filename will no longer fail to load and now behave as any
    other spec. Fixes
    [#&#8203;18871](https://togithub.com/cypress-io/cypress/issues/18871).
-   When using the Selector Playground, the HTML attribute's value will be wrapped
    in double-quotes. Fixes
    [#&#8203;1884](https://togithub.com/cypress-io/cypress/issues/1884).
-   The call count is now shown in the Command Log when using
    `cy.stub().log(false)`. Fixes
    [#&#8203;18907](https://togithub.com/cypress-io/cypress/issues/18907).
-   The warning message for retrying connection to a browser has been improved to
    indicate when it is still waiting. Fixes
    [#&#8203;18644](https://togithub.com/cypress-io/cypress/issues/18644).
-   Cypress commands that rely on `this` context now have access to `this` when
    overridden. Fixes [#&#8203;18899](https://togithub.com/cypress-io/cypress/pull/18899).

### [`v9.0.0`](https://togithub.com/cypress-io/cypress/releases/v9.0.0)

[Compare Source](https://togithub.com/cypress-io/cypress/compare/v8.7.0...v9.0.0)

*Released 11/10/2021*

**Breaking Changes:**

-   The `nodeVersion` configuration option now defaults to `system`. The behavior
    of the `system` option has changed to always use the Node.js binary/version
    that launched Cypress. If Cypress was not launched via the terminal, Cypress
    will use the `bundled` Node.js version. This could change the behavior of code
    within your `pluginsFile` since it may be run in your `system` Node.js
    version. Addresses
    [#&#8203;18684](https://togithub.com/cypress-io/cypress/issues/18684).
-   Windows 32-bit is no longer supported in Cypress. Addresses
    [#&#8203;17962](https://togithub.com/cypress-io/cypress/issues/17962).
-   An error will now be thrown if an invalid value is passed to `Cypress.config`.
    Previously invalid values were ignored and could cause unexpected behavior.
    Addresses [#&#8203;18589](https://togithub.com/cypress-io/cypress/pull/18589).
-   `cy.contains()` no longer yields the `<body>` element when it matches the
    content of `<script>` or `<style>` tags. Addresses
    [#&#8203;14861](https://togithub.com/cypress-io/cypress/issues/14861).
-   Attempting to add an existing built-in Cypress command using
    `Cypress.Commands.add()` will now throw an error, indicating that
    `Cypress.Commands.overwrite()` should be used instead to overwrite the
    behavior of existing commands. Addresses
    [#&#8203;18572](https://togithub.com/cypress-io/cypress/issues/18572).
-   Custom command implementations are now typed based on the declared custom
    chainables. Addresses
    [#&#8203;17496](https://togithub.com/cypress-io/cypress/issues/17496).
-   The bundled Node.js version was upgraded from `14.17.0` to `16.5.0`. This
    could change the behavior of code within the `pluginsFile` when using the
    bundled Node.js version of Cypress. Addressed in
    [#&#8203;18317](https://togithub.com/cypress-io/cypress/pull/18317).

**Deprecations:**

-   The `nodeVersion` configuration option has been deprecated and will be removed
    in a future release.

**Features:**

-   When `null` is passed as the encoding to `cy.readFile()` or `cy.fixture()`,
    the file is treated as binary and read as a Buffer. Similarly, `null` passed
    as the encoding to `cy.writeFile()` allows direct writing of buffers. If the
    encoding is unspecified, the default remains `utf8`, matching the current
    behavior. Addresses
    [#&#8203;18534](https://togithub.com/cypress-io/cypress/issues/18534).

**Bugfixes:**

-   Sticky elements within a fixed container will now be able to be properly
    scrolled to during action commands. Fixes
    [#&#8203;4233](https://togithub.com/cypress-io/cypress/issues/4233).
-   `document.referrer` will now correctly reflect the correct value from the
    application under test after `cy.visit()`. Fixes
    [#&#8203;4295](https://togithub.com/cypress-io/cypress/issues/4295).

**Dependencies:**

-   Upgraded Chrome browser version used during `cypress run` and when selecting
    Electron browser in `cypress open` from `91` to `94`. Addressed in
    [#&#8203;15292](https://togithub.com/cypress-io/cypress/pull/18317).
-   Upgraded bundled Node.js version from `14.17.0` to `16.5.0`. Addressed in
    [#&#8203;15292](https://togithub.com/cypress-io/cypress/pull/18317).
-   Upgraded `electron` from `14.1.0` to `15.2.0`. Addressed in
    [#&#8203;15292](https://togithub.com/cypress-io/cypress/pull/18317).

</details>

---

### Configuration

📅 **Schedule**: "every weekend" (UTC).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Renovate will not automatically rebase this PR, because other commits have been found.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox.

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#github/carbon-design-system/carbon-for-ibm-dotcom).